name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  package:
    name: Validate package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tea-spoons/unity-ci-kit/actions/validate-package@v0
        with:
          package-path: .
